### ISSUE TITLE
Name Collision with Windows Fax and Scan when installed globally with npm on Win10

### ISSUE THREAD

**Issue by Mahog** [Webstrates/file-system#13]
When installing file-system through ```npm install -g``` on Windows 10, the ```wfs``` command does not reference webstrates file-system. Instead, [Windows Fax and Scan ](https://en.wikipedia.org/wiki/Windows_Fax_and_Scan) is started. This service is installed on every Windows 10 machine and will be launched when running ```wfs``` from both cmd and git-bash.

A quick workaround that worked for me was to rename the files named wfs and wfs.cmd in C:\Users\\<User\>\AppData\Roaming\npm. As a permanent fix, I recommend renaming the path variable in the bin property in package.json.

**Comment by kbadk** [comment]
You can now use `webstratesfs` instead of `wfs`. `wfs` is still available on other platforms. Update the package to get started.

However, I'd be remiss to not recommend you install the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) on your Windows installation and use that instead. The fact that wfs works on Windows at all is more coincidental than deliberate as I've never tested on any non-Unix-based systems and don't anticipate I'll begin to.
