### ISSUE TITLE
HTML comments can cause the output to be garbled

### ISSUE THREAD

**Issue by svnhub** [Webstrates/file-system#7]
In certain cases HTML comments in the input can cause the output to be almost entirely discarded with the exception of the contents of the comment. Example filesystem edit:
```
<!DOCTYPE html>
<!-- This shouldn't be the output -->
<html>
<body>
<div>TODO write content</div>
</body>
</html>
```
returns the following output in the webstrate:
`<!-- This shouldn't be the output -->`
and nothing else.

**Comment by kbadk** [comment]
This isn't actually a bug. The problem is that an HTML document (if we disregard the `DOCTYPE`) is a tree. If you add a comment (or anything at all for that matter) outside the HTML tag, you have two roots and thus two trees.

I suppose we could fix this, but it'd be dirty and ugly, so instead: Just make sure that the document only has one tree/root, preferably the `<html>` tag.

As a side note: File system has explicit "support for" `DOCTYPE`s in the sense that we find one, we discard it. The Webstrates platform gets served in standards mode, so regardless of what we do to the DOM afterwards, it'll remain in standards mode.

**Comment by svnhub** [comment]
Ok, just letting you know =)

The format above unfortunately happens to be the default HTML5 template in Netbeans where the comment contains a bit of information about the project and the user who instantiated the template. That's how I ended up in the situation in the first place.
